# Generated by Django 3.2.8 on 2021-12-21 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_name', models.CharField(max_length=50)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.account')),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('tweet', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('hashtag', models.ManyToManyField(blank=True, related_name='hashtag', to='data.Hashtags')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('twitter_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.account')),
                ('twitter_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='BaseballData',
        ),
        migrations.AddField(
            model_name='likes',
            name='main_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.tweets'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
