# Generated by Django 3.2.8 on 2021-12-22 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20211221_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('date1', models.TextField(null=True)),
                ('date2', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='likes',
            name='account',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='main_tweet',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='like',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='twitter_account',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='twitter_user',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='twitter_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='twitter_user',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='Hashtags',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
        migrations.AddField(
            model_name='images',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.account'),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
