# Generated by Django 3.2.8 on 2021-12-22 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
