# Generated by Django 3.2.8 on 2021-12-22 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_images_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='pic',
        ),
    ]
