# Generated by Django 3.2.8 on 2021-12-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_images_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='images',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
    ]
