# Generated by Django 3.2.8 on 2021-12-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20211222_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
