# Generated by Django 3.2.8 on 2021-12-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_images_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='pic',
        ),
        migrations.AddField(
            model_name='images',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
