# Generated by Django 3.2.8 on 2021-12-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20211222_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pitches',
            field=models.TextField(null=True),
        ),
    ]
